# Generated by Django 5.2.7 on 2025-10-28 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0002_rename_notes_note"),
    ]

    operations = [
        migrations.RenameField(
            model_name="note",
            old_name="tittle",
            new_name="title",
        ),
    ]
